[package]
name = "drone_network"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
plotters = "0.3.7"
petgraph = "0.6.5"
rustworkx-core = "0.15.1"
ctrlc-async = "3.2.2"
clap = "4.5.21"
